version: "3.9"

services:
  note-service:
    build:
      context: ./note-service
      dockerfile: Dockerfile
    container_name: note_service
    ports:
      - "8081:8081"
    environment:
      PG_HOST: notes-db
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: admin
      PG_DB: notesdb
      JWT_SECRET: "super-secret-key"
      KAFKA_BROKER: "kafka:9092"
      KAFKA_USER_REGISTERED_TOPIC: "user_registered"
      REDIS_ADDR: "redis:6379"
      REDIS_DB: "0"
    depends_on:
      notes-db:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "8082:8082"
    environment:
      PG_HOST: users-db
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: admin
      PG_DB: usersdb
      JWT_SECRET: "super-secret-key"
      KAFKA_BROKER: "kafka:9092"
      KAFKA_USER_REGISTERED_TOPIC: "user_registered"
    depends_on:
      users-db:
        condition: service_healthy
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"    

  notes-db:
    image: postgres:15
    container_name: notes_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: notesdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - notes_pgdata:/var/lib/postgresql/data
      - ./note-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  users-db:
    image: postgres:15
    container_name: users_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: usersdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - users_pgdata:/var/lib/postgresql/data
      - ./user-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"

volumes:
  notes_pgdata:
  users_pgdata:
